spring.application.name=Clinica

spring.datasource.url=jdbc:postgresql://localhost:5432/clinicaOdoRest
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=10

#Para mostrar en la consola las consultas que se realizen a la base de datos
spring.jpa.show-sql=true
#Sirve para que si se realiza algun cambio en nuestras clases como agregar columnas se refleje en las tablas de la BD
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


